### PR TITLE
Handle varying output formats for rbd status

### LINKED ISSUE #451: Ceph Kraken/RBD causes Go panic
# Summary
When using ceph-common from the Kraken release instead of eg. Jewel, a go panic arises whenever image status is probed. I assume the problem is in libstorage (but I may be mistaken...) since that is where the go panic arises.

    REX-Ray
    -------
    Binary: /usr/bin/rexray
    Flavor: client+agent+controller
    SemVer: 0.8.1
    OsArch: Linux-x86_64
    Branch: v0.8.1
    Commit: 30e9082dd9917f0d218ca981f886d701110ce5f5
    Formed: Sat, 25 Feb 2017 04:00:28 CET
    
    libStorage
    ----------
    SemVer: 0.5.1
    OsArch: Linux-x86_64
    Branch: v0.8.1
    Commit: 35c7b6d96d5f17aa0c0379924615ae22c1ad3d45
    Formed: Sat, 25 Feb 2017 03:59:00 CET

# Bug Reports
Go panic with rbd driver with Ceph Kraken

## Expected Behavior
    rexray volume ls
lists images, like

    ID             Name       Status     Size
    rbd.test-rbs   test-rbs   available  0
    rbd.test-rbs2  test-rbs2  available  0
    rbd.testfoo    testfoo    available  0

## Actual Behavior
    [...]
    DEBU[0002] running command: [rbd ls -p rbd -l --format json]
    DEBU[0002] running command: [rbd status --pool rbd test-rbs --format json]
    DEBU[0002] task completed                                host=unix:///var/run/libstorage/656583153.sock instanceID=rbd=172.20.8.28 route=volumesForService server=nebula-piper-je service=rbd storageDriver=rbd task=0 time=1488873908773 tls=false txCR=1488873908 txID=236dd599-bc14-49dd-4b17-ccb846e8e24e
    panic: interface conversion: interface {} is []interface {}, not map[string]interface {}
    
    goroutine 68 [running]:
    panic(0x126b7a0, 0xc420321400)
            /home/travis/.gimme/versions/go1.7.5.linux.amd64/src/runtime/panic.go:500 +0x1a1
    github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/drivers/storage/rbd/utils.RBDHasWatchers(0xc4202d62c0,0xc4202d62a0, 0xc42024ae80, 0xc, 0x214efa0)
            /home/travis/gopath/src/github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/drivers/storage/rbd/utils/utils.go:339 +0xdf
    github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/drivers/storage/rbd/storage.(*driver).toTypeVolumes(0xc4204d8a00, 0x1d898c0, 0xc42005a420, 0xc420243d80, 0x3, 0x4, 0x1, 0x0, 0xc4202a4a00, 0x0, ...)
            /home/travis/gopath/src/github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/drivers/storage/rbd/storage/rbd_storage.go:416 +0x66d
    github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/drivers/storage/rbd/storage.(*driver).Volumes(0xc4204d8a00, 0x1d898c0, 0xc42005a420, 0xc4203788c0, 0xc42005a420, 0x4fa79f, 0xc4202a49c0, 0xc42027d630, 0x1)
            /home/travis/gopath/src/github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/drivers/storage/rbd/storage/rbd_storage.go:92 +0x103
    github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/registry.(*sdm).Volumes(0xc420200660, 0x1d898c0, 0xc42005a420, 0xc4203788c0, 0xc42027d640, 0x1d87c00, 0xc42027d620, 0xc42004e3ec, 0xc420142b60)
            /home/travis/gopath/src/github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/registry/registry_storage.go:64 +0xb4
    github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/router/volume.getFilteredVolumes(0x1d898c0,0xc42005a420, 0xc4200be780, 0x1d87840, 0xc420320000, 0x1d82020, 0xc4202a5500, 0xc4203788c0, 0x0, 0xc42027d220, ...)
            /home/travis/gopath/src/github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/router/volume/volume_routes.go:233 +0x281
    github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/router/volume.(*router).volumesForService.func1(0x1d898c0, 0xc42005a420, 0x1d82020, 0xc4202a5500, 0xc42027d230, 0xc42000d9a0, 0x14813d0, 0xc)
            /home/travis/gopath/src/github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/router/volume/volume_routes.go:119 +0x80
    github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/services.execTask(0xc42029ed80)
            /home/travis/gopath/src/github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/services/services_task.go:78 +0x732
    github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/services.(*storageService).Init.func1(0xc4202a5500)
            /home/travis/gopath/src/github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/services/services_storage.go:29 +0x73
    created by github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/services.(*storageService).Init
            /home/travis/gopath/src/github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/services/services_storage.go:31 +0xc8

## Steps To Reproduce
Upgrade ceph-common and dependencies to Ceph Kraken (from Ceph Jewel) on Debian Jessie or Ubuntu Xenial. Try to run rexray volume ls with the previously working configuration (as included below)

## Configuration Files

```yaml
#/etc/rexray/config.yml
libstorage:
  logging:
    level: debug
    httpRequests:  true
    httpResponses: true
  service: rbd
rbd:
  defaultPool: rbd
```

### Client Log
https://gist.github.com/srhb/f3bba02f50790762b6e4fbf943d6dfc4

The problem disappears immediately with a downgrade to the Jewel version of ceph-common

### PR DESCRIPTION
**Pull request by codenrhoden**
The output for rbd status --format json has been updated recently
to have the "watchers" field be an array instead of a map. Account
for that.

Fixes #451

### CODE REVIEW

File: drivers/storage/rbd/storage/rbd_storage.go [hunk 1]
```diff
@@ -47,7 +45,7 @@ func (d *driver) Name() string {
 // Init initializes the driver.
 func (d *driver) Init(context types.Context, config gofig.Config) error {
```
Comment (akutz) [inline drivers/storage/rbd/storage/rbd_storage.go]: Hi @codenrhoden,

Since this PR needs to be rebased onto `master` anyway, can you please fix the name of the `context` variable to be `ctx`. It's the standard way of naming the first parameter of a function when it's of type `Context`. Thank you.

File: drivers/storage/rbd/utils/utils.go [hunk 2]
```diff
@@ -58,16 +58,16 @@ type RBDInfo struct {
 }
 
 //GetRadosPools returns a slice containing all the pool names
-func GetRadosPools() ([]*string, error) {
+func GetRadosPools(ctx types.Context) ([]*string, error) {
 
 	cmd := exec.Command(radosCmd, "lspools")
-	log.Debugf("running command: %v", cmd.Args)
+	ctx.Debugf("running command: %v", cmd.Args)
```
Comment (akutz) [inline drivers/storage/rbd/utils/utils.go]: Hi @codenrhoden,

Please use this instead:

```go
ctx.WithFields(map[string]interface{}{
	"cmd":  radosCmd,
	"args": cmd.Args,
}).Debug("running rados cmd")
```

File: drivers/storage/rbd/utils/utils.go [hunk 3]
```diff
@@ -58,16 +58,16 @@ type RBDInfo struct {
...
 
 	out, err := cmd.Output()
 	if err != nil {
 		if exiterr, ok := err.(*exec.ExitError); ok {
 			stderr := string(exiterr.Stderr)
-			log.Errorf("Unable to get pools: %s", stderr)
+			ctx.Errorf("Unable to get pools: %s", stderr)
```
Comment (akutz) [inline drivers/storage/rbd/utils/utils.go]: Hi @codenrhoden,

Please use this instead (formatting aside):

```go
ctx.WithError(
	exiterr,
).WithField(
	"stderr", stderr,
).Error("error getting pools")
```

File: drivers/storage/rbd/utils/utils.go [hunk 4]
```diff
@@ -87,16 +87,16 @@ func GetRadosPools() ([]*string, error) {
...
 	cmd := exec.Command(rbdCmd, "ls", "-p", *pool, "-l", formatOpt, jsonArg)
-	log.Debugf("running command: %v", cmd.Args)
+	ctx.Debugf("running command: %v", cmd.Args)
 
 	out, err := cmd.Output()
 	if err != nil {
 		if exiterr, ok := err.(*exec.ExitError); ok {
 			stderr := string(exiterr.Stderr)
-			log.Errorf("Unable to get rbd images: %s", stderr)
+			ctx.Errorf("Unable to get rbd images: %s", stderr)
```
Comment (akutz) [inline drivers/storage/rbd/utils/utils.go]: Hi @codenrhoden,

Please use this instead (formatting aside):

```go
ctx.WithError(
	exiterr,
).WithField(
	"stderr", stderr,
).Error("error getting rbd images")
```

File: drivers/storage/rbd/utils/utils.go [hunk 5]
```diff
@@ -120,12 +120,15 @@ func GetRBDImages(pool *string) ([]*RBDImage, error) {
...
+func GetRBDInfo(
+	ctx types.Context,
+	pool *string,
+	name *string) (*RBDInfo, error) {
 
 	cmd := exec.Command(
 		rbdCmd, "info", "-p", *pool, *name, formatOpt, jsonArg)
 
-	log.Debugf("running command: %v", cmd.Args)
+	ctx.Debugf("running command: %v", cmd.Args)
```
Comment (akutz) [inline drivers/storage/rbd/utils/utils.go]: Hi @codenrhoden,

Please use this instead:

```go
ctx.WithFields(map[string]interface{}{
	"cmd":  rbdCmd,
	"args": cmd.Args,
}).Debug("running rados cmd")
```

File: drivers/storage/rbd/utils/utils.go [hunk 6]
```diff
@@ -138,7 +141,7 @@ func GetRBDInfo(pool *string, name *string) (*RBDInfo, error) {
 				}
 			}
 			stderr := string(exiterr.Stderr)
-			log.Errorf("Unable to get rbd info: %s", stderr)
+			ctx.Errorf("Unable to get rbd info: %s", stderr)
```
Comment (akutz) [inline drivers/storage/rbd/utils/utils.go]: Hi @codenrhoden,

Please use this instead (formatting aside):

```go
ctx.WithError(
	exiterr,
).WithField(
	"stderr", stderr,
).Error("error getting rbd info")
```

File: drivers/storage/rbd/utils/utils.go [hunk 7]
```diff
@@ -167,14 +170,14 @@ func GetVolumeID(pool, image *string) *string {
...
-func GetMappedRBDs() (map[string]string, error) {
+func GetMappedRBDs(ctx types.Context) (map[string]string, error) {
 
 	out, err := exec.Command(
 		rbdCmd, "showmapped", formatOpt, jsonArg).Output()
 	if err != nil {
 		if exiterr, ok := err.(*exec.ExitError); ok {
 			stderr := string(exiterr.Stderr)
-			log.Errorf("Unable to get rbd map: %s", stderr)
+			ctx.Errorf("Unable to get rbd map: %s", stderr)
```
Comment (akutz) [inline drivers/storage/rbd/utils/utils.go]: Hi @codenrhoden,

Please use this instead (formatting aside):

```go
ctx.WithError(
	exiterr,
).WithField(
	"stderr", stderr,
).Error("error getting rbd map")
```

File: drivers/storage/rbd/utils/utils.go [hunk 8]
```diff
@@ -167,14 +170,14 @@ func GetVolumeID(pool, image *string) *string {
 }
 
 //GetMappedRBDs returns a map of RBDs currently mapped to the *local* host
-func GetMappedRBDs() (map[string]string, error) {
+func GetMappedRBDs(ctx types.Context) (map[string]string, error) {
 
 	out, err := exec.Command(
```
Comment (akutz) [inline drivers/storage/rbd/utils/utils.go]: Hi @codenrhoden,

Did you want to add logging here?

```go
cmd := exec.Command(
  	rbdCmd, "info", "-p", *pool, *name, formatOpt, jsonArg)

ctx.WithFields(map[string]interface{}{
	"cmd":  rbdCmd,
	"args": cmd.Args,
}).Debug("running rados cmd")

out, err := cmd.Output()
```

File: drivers/storage/rbd/utils/utils.go [hunk 9]
```diff
@@ -87,16 +87,16 @@ func GetRadosPools() ([]*string, error) {
 }
 
 //GetRBDImages returns a slice of RBD image info
-func GetRBDImages(pool *string) ([]*RBDImage, error) {
+func GetRBDImages(ctx types.Context, pool *string) ([]*RBDImage, error) {
 
 	cmd := exec.Command(rbdCmd, "ls", "-p", *pool, "-l", formatOpt, jsonArg)
-	log.Debugf("running command: %v", cmd.Args)
+	ctx.Debugf("running command: %v", cmd.Args)
```
Comment (akutz) [inline drivers/storage/rbd/utils/utils.go]: Hi @codenrhoden,

Please use this instead:

```go
ctx.WithFields(map[string]interface{}{
	"cmd":  rbdCmd,
	"args": cmd.Args,
}).Debug("running rados cmd")
```

File: drivers/storage/rbd/utils/utils.go [hunk 10]
```diff
@@ -219,14 +223,14 @@ func RBDCreate(
 	}
 
 	cmd.Args = append(cmd.Args, *image)
-	log.Debugf("running command: %v", cmd.Args)
+	ctx.Debugf("running command: %v", cmd.Args)
```
Comment (akutz) [inline drivers/storage/rbd/utils/utils.go]: Hi @codenrhoden,

Please use this instead:

```go
ctx.WithFields(map[string]interface{}{
	"cmd":  rbdCmd,
	"args": cmd.Args,
}).Debug("running rados cmd")
```

File: drivers/storage/rbd/utils/utils.go [hunk 11]
```diff
@@ -219,14 +223,14 @@ func RBDCreate(
...
 
 	err := cmd.Run()
 
 	if err != nil {
 		if exiterr, ok := err.(*exec.ExitError); ok {
 			stderr := string(exiterr.Stderr)
-			log.Errorf("Unable to create RBD: %s", stderr)
+			ctx.Errorf("Unable to create RBD: %s", stderr)
```
Comment (akutz) [inline drivers/storage/rbd/utils/utils.go]: Hi @codenrhoden,

Please use this instead (formatting aside):

```go
ctx.WithError(
	exiterr,
).WithField(
	"stderr", stderr,
).Error("error creating rbd")
```

File: drivers/storage/rbd/utils/utils.go [hunk 12]
```diff
@@ -237,17 +241,17 @@ func RBDCreate(
...
 	)
-	log.Debugf("running command: %v", cmd.Args)
+	ctx.Debugf("running command: %v", cmd.Args)
 
 	err := cmd.Run()
 	if err != nil {
 		if exiterr, ok := err.(*exec.ExitError); ok {
 			stderr := string(exiterr.Stderr)
-			log.Errorf("Unable to delete RBD: %s", stderr)
+			ctx.Errorf("Unable to delete RBD: %s", stderr)
```
Comment (akutz) [inline drivers/storage/rbd/utils/utils.go]: Hi @codenrhoden,

Please use this instead (formatting aside):

```go
ctx.WithError(
	exiterr,
).WithField(
	"stderr", stderr,
).Error("error deleting rbd")
```

File: drivers/storage/rbd/utils/utils.go [hunk 13]
```diff
@@ -237,17 +241,17 @@ func RBDCreate(
 }
 
 //RBDRemove deletes the RBD volume on the cluster
-func RBDRemove(pool *string, image *string) error {
+func RBDRemove(ctx types.Context, pool *string, image *string) error {
 	cmd := exec.Command(rbdCmd, "rm", poolOpt, *pool, "--no-progress",
 		*image,
 	)
-	log.Debugf("running command: %v", cmd.Args)
+	ctx.Debugf("running command: %v", cmd.Args)
```
Comment (akutz) [inline drivers/storage/rbd/utils/utils.go]: Hi @codenrhoden,

Please use this instead:

```go
ctx.WithFields(map[string]interface{}{
	"cmd":  rbdCmd,
	"args": cmd.Args,
}).Debug("running rados cmd")
```

File: drivers/storage/rbd/utils/utils.go [hunk 14]
```diff
@@ -258,16 +262,16 @@ func RBDRemove(pool *string, image *string) error {
 }
 
 //RBDMap attaches the given RBD image to the *local* host
-func RBDMap(pool, image *string) (string, error) {
+func RBDMap(ctx types.Context, pool, image *string) (string, error) {
 
 	cmd := exec.Command(rbdCmd, "map", poolOpt, *pool, *image)
-	log.Debugf("running command: %v", cmd.Args)
+	ctx.Debugf("running command: %v", cmd.Args)
```
Comment (akutz) [inline drivers/storage/rbd/utils/utils.go]: Hi @codenrhoden,

Please use this instead:

```go
ctx.WithFields(map[string]interface{}{
	"cmd":  rbdCmd,
	"args": cmd.Args,
}).Debug("running rados cmd")
```

File: drivers/storage/rbd/utils/utils.go [hunk 15]
```diff
@@ -258,16 +262,16 @@ func RBDRemove(pool *string, image *string) error {
...
 
 	out, err := cmd.Output()
 	if err != nil {
 		if exiterr, ok := err.(*exec.ExitError); ok {
 			stderr := string(exiterr.Stderr)
-			log.Errorf("Unable to map RBD: %s", stderr)
+			ctx.Errorf("Unable to map RBD: %s", stderr)
```
Comment (akutz) [inline drivers/storage/rbd/utils/utils.go]: Hi @codenrhoden,

Please use this instead (formatting aside):

```go
ctx.WithError(
	exiterr,
).WithField(
	"stderr", stderr,
).Error("error mapping rbd")
```

File: drivers/storage/rbd/utils/utils.go [hunk 16]
```diff
@@ -279,16 +283,16 @@ func RBDMap(pool, image *string) (string, error) {
...
 	cmd := exec.Command(rbdCmd, "unmap", *device)
-	log.Debugf("running command: %v", cmd.Args)
+	ctx.Debugf("running command: %v", cmd.Args)
 
 	err := cmd.Run()
 	if err != nil {
 		if exiterr, ok := err.(*exec.ExitError); ok {
 			stderr := string(exiterr.Stderr)
-			log.Errorf("Unable to unmap RBD: %s", stderr)
+			ctx.Errorf("Unable to unmap RBD: %s", stderr)
```
Comment (akutz) [inline drivers/storage/rbd/utils/utils.go]: Hi @codenrhoden,

Please use this instead (formatting aside):

```go
ctx.WithError(
	exiterr,
).WithField(
	"stderr", stderr,
).Error("error unmapping rbd")
```

File: drivers/storage/rbd/utils/utils.go [hunk 17]
```diff
@@ -299,18 +303,20 @@ func RBDUnmap(device *string) error {
...
 	)
-	log.Debugf("running command: %v", cmd.Args)
+	ctx.Debugf("running command: %v", cmd.Args)
 
 	out, err := cmd.Output()
 	if err != nil {
 		if exiterr, ok := err.(*exec.ExitError); ok {
 			stderr := string(exiterr.Stderr)
-			log.Errorf("Unable to get RBD status: %s", stderr)
+			ctx.Errorf("Unable to get RBD status: %s", stderr)
```
Comment (akutz) [inline drivers/storage/rbd/utils/utils.go]: Hi @codenrhoden,

Please use this instead (formatting aside):

```go
ctx.WithError(
	exiterr,
).WithField(
	"stderr", stderr,
).Error("error getting rbd status")
```

File: drivers/storage/rbd/utils/utils.go [hunk 18]
```diff
@@ -279,16 +283,16 @@ func RBDMap(pool, image *string) (string, error) {
 }
 
 //RBDUnmap detaches the given RBD device from the *local* host
-func RBDUnmap(device *string) error {
+func RBDUnmap(ctx types.Context, device *string) error {
 
 	cmd := exec.Command(rbdCmd, "unmap", *device)
-	log.Debugf("running command: %v", cmd.Args)
+	ctx.Debugf("running command: %v", cmd.Args)
```
Comment (akutz) [inline drivers/storage/rbd/utils/utils.go]: Hi @codenrhoden,

Please use this instead:

```go
ctx.WithFields(map[string]interface{}{
	"cmd":  rbdCmd,
	"args": cmd.Args,
}).Debug("running rados cmd")
```

File: drivers/storage/rbd/utils/utils.go [hunk 19]
```diff
@@ -299,18 +303,20 @@ func RBDUnmap(device *string) error {
...
-func GetRBDStatus(pool, image *string) (map[string]interface{}, error) {
+func GetRBDStatus(
+	ctx types.Context,
+	pool, image *string) (map[string]interface{}, error) {
 
 	cmd := exec.Command(
 		rbdCmd, "status", poolOpt, *pool, *image, formatOpt, jsonArg,
 	)
-	log.Debugf("running command: %v", cmd.Args)
+	ctx.Debugf("running command: %v", cmd.Args)
```
Comment (akutz) [inline drivers/storage/rbd/utils/utils.go]: Hi @codenrhoden,

Please use this instead:

```go
ctx.WithFields(map[string]interface{}{
	"cmd":  rbdCmd,
	"args": cmd.Args,
}).Debug("running rados cmd")
```

**Review by akutz — CHANGES_REQUESTED** [review]

**Comment by codenrhoden** [comment]
Thanks for the guidance on better structured logging, @akutz. A definite improvement. I think I've made all the requested changes.
